sort:main.o selection.o bubble.o insertion.o
	gcc -o sort ./../object/main.o ./../object/selection.o ./../object/bubble.o ./../object/insertion.o
main.o:
	gcc  -c main.c -o  ./../object/main.o -I ./../header
selection.o:
	gcc -c selection.c -o ./../object/selection.o -I ./../header
bubble.o:
	gcc -c bubble.c -o ./../object/bubble.o	-I ./../header
insertion.o:
	gcc -c insertion.c -o ./../object/insertion.o -I ./../header




